// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Minshenyao",
            "url": "https://www.github.com/Minshenyao"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/GetTaskAuditDetail": {
            "post": {
                "description": "获取任务报名详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "获取任务报名详情",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "taskId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/approveVolunteer": {
            "post": {
                "description": "通过报名人审核",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "通过报名人审核",
                "parameters": [
                    {
                        "type": "string",
                        "name": "email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "taskId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/create_task": {
            "post": {
                "description": "创建新的志愿者活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "创建新任务",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "任务信息",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TaskInfo"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/admin/delete_task/{id}": {
            "delete": {
                "description": "删除指定活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "删除任务",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "活动ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/getTaskDetails": {
            "get": {
                "description": "获取任务详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "获取任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/rejectVolunteer": {
            "post": {
                "description": "拒绝报名人审核",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "拒绝报名人审核",
                "parameters": [
                    {
                        "type": "string",
                        "name": "email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "taskId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/update": {
            "post": {
                "description": "更新指定活动的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "更新任务",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "任务信息",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TaskInfo"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/login": {
            "post": {
                "description": "用户登录并生成 token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "登录用户",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginUserRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "注册新用户",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/task/getStatus": {
            "get": {
                "description": "获取当前用户任务状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "获取任务状态",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/task/join": {
            "post": {
                "description": "用户加入任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "加入任务",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "任务信息",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TaskInfo"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/task/tasks": {
            "get": {
                "description": "获取所有活动列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "获取所有任务",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/change_password": {
            "put": {
                "description": "修改用户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改密码信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/profile": {
            "get": {
                "description": "获取当前登录用户的个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/update_user_info": {
            "put": {
                "description": "更新用户的个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserInfoRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/upload_avatar": {
            "post": {
                "description": "用户上传头像",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "上传用户头像",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户头像文件",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/volunteer_count": {
            "get": {
                "description": "统计所有志愿者用户个数，返回姓名、服务时长、状态、最近一次登录时间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "统计志愿者用户个数",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIsInR5cCI6IkpXJ9...",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "dto.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "dto.LoginUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "123@qq.com"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "dto.RegisterUserRequest": {
            "type": "object",
            "required": [
                "email",
                "gender",
                "nickname",
                "password",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "123@qq.com"
                },
                "gender": {
                    "type": "string",
                    "example": "男"
                },
                "nickname": {
                    "type": "string",
                    "example": "user01"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "13812345678"
                }
            }
        },
        "dto.TaskInfo": {
            "type": "object",
            "required": [
                "created_at",
                "end_time",
                "id",
                "joined",
                "limit",
                "location",
                "name",
                "start_time"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "joined": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserInfoRequest": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "志愿者系统",
	Description:      "一个简单的志愿者管理系统，包括用户注册、登录和志愿任务的创建、删除、修改、查找等",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
